name: CloudflareSpeedTest CI
on: [push, pull_request]
env:
  GO_VERSION: 1.21.7
  PKG_NAME: github.com/XIU2/CloudflareSpeedTest
jobs:
  build:
    name: Build ${{ matrix.os }} (${{ matrix.arch }})
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        include:
          - os: ubuntu-latest
            arch: amd64
            tags: linux_amd64
          - os: ubuntu-latest
            arch: arm64
            tags: linux_arm64
          - os: macos-latest
            arch: amd64
            tags: darwin_amd64
          - os: macos-latest
            arch: arm64
            tags: darwin_arm64
          - os: windows-latest
            arch: amd64
            tags: windows_amd64
            ext: .exe
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - uses: actions/setup-go@v5
        with:
          go-version: ${{ env.GO_VERSION }}
      - name: Build Version Info
        id: version
        shell: bash # 关键修复：所有平台统一使用 Bash
        run: |
          GIT_TAG=$(git describe --tags --abbrev=0 || echo "v0.0.0")
          GIT_COMMIT=$(git rev-parse --short HEAD)
          echo "VERSION=${GIT_TAG}-${GIT_COMMIT}" >> $GITHUB_ENV
      - name: Build Binary
        shell: bash # 新增关键配置：强制使用 Bash
        env:
          CGO_ENABLED: 0
          GOOS: ${{ contains(matrix.os, 'windows') && 'windows' || contains(matrix.os, 'macos') && 'darwin' || 'linux' }}
          GOARCH: ${{ matrix.arch }}
        run: |
          OUTPUT="CloudflareSpeedTest${{ matrix.ext || '' }}"
          LDFLAGS="-X main.version=${{ env.VERSION }} -s -w"
          go build -trimpath -ldflags "$LDFLAGS" -o $OUTPUT

      - uses: actions/upload-artifact@v4
        with:
          name: CloudflareSpeedTest_${{ matrix.tags }}
          path: CloudflareSpeedTest*
          retention-days: 3
